name: Build and Test

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build wrapper.exe
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: pwsh
        run: .\build.ps1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wrapper
          path: wrapper.exe
          retention-days: 1

  test:
    name: Test wrapper
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: wrapper
          path: .
      - name: Download official adb/fastboot
        shell: pwsh
        run: |
          $url = "https://dl.google.com/android/repository/platform-tools-latest-windows.zip"
          $zip = "$env:TEMP\platform-tools.zip"
          Invoke-WebRequest -Uri $url -OutFile $zip
          Expand-Archive -Path $zip -DestinationPath "$env:TEMP\platform-tools"
          # Копируем все файлы из папки platform-tools в текущую папку
          Copy-Item "$env:TEMP\platform-tools\platform-tools\*" -Destination "." -Recurse
          # Переименовываем adb.exe и fastboot.exe в .real.exe
          Rename-Item ".\adb.exe" "adb.real.exe"
          Rename-Item ".\fastboot.exe" "fastboot.real.exe"
      - name: Prepare wrappers
        shell: pwsh
        run: |
          Copy-Item ".\wrapper.exe" -Destination ".\adb.exe"
          Copy-Item ".\wrapper.exe" -Destination ".\fastboot.exe"
      - name: Run tests
        shell: pwsh
        run: .\test.ps1